// AUTOMATICALLY GENERATED FILE. DO NOT EDIT.

package main

var handlersTmpl = tmpl(asset.init(asset{Name: "handlers.go.tmpl", Content: "" +
	"// generated by {{ .Prgm }}; DO NOT EDIT\n\npackage {{ .PkgName }}\n\nimport (\n\t\"net/http\"\n)\n\n// registerAPIHandlers registers resource handlers for each unique named route of the API.\nfunc (h *Handler) registerAPIHandlers() {\n{{ range .Routes }}\th.Routes.r.Get(\"{{ .Name }}\").Handler(&MethodHandler{\n{{ $route := . }}{{ range .Methods }}\t{{ . | tolower | capitalize }}: endpointHandler(func(w http.ResponseWriter, r *http.Request) *endpointError {\n        {{ range $route.RouteParams }}{{ .Varname }}, err := h.getUID(w, r, \"{{ .Name }}\")\n\tif err != nil {\n\t\treturn newEndpointError(err, http.StatusBadRequest)\n\t}\n\t{{end}}\treturn h.{{ . | tolower }}{{ $route.FuncBaseName }}(w, r{{ range $route.RouteParams }},{{ .Varname }}{{end}})\n}),\n{{end}}\n})\n{{end}}}\n" +
	""}))
