// AUTOMATICALLY GENERATED FILE. DO NOT EDIT.

package dispel

var routesTmpl = tmpl(asset.init(asset{Name: "routes.go.tmpl", Content: "" +
	"// generated by {{ .Prgm }}; DO NOT EDIT\n\npackage {{ .PkgName }}\n\nimport (\n\t\"net/url\"\n)\n\n// setupRoutes registers the url path and name of all routes of the API.\nfunc (r *Routes) setupRoutes() {\n{{ range .Routes.ByResource }}\tr.r.Path(\"{{ .Path }}\").Name(\"{{ .Name }}\")\n{{end}}}\n\n// URL builders\n\n{{ range .Routes.ByResource }}func (r *Routes) {{ .Name | symbolName }}({{ range .RouteParams }}{{ .Varname }} string,{{end}}) *url.URL {\n\treturn r.routeURL(\"{{ .Name }}\", {{ range .RouteParams }}\"{{ .Name }}\", {{ .Varname }},{{end}})\n}\n{{end}}" +
	""}))
