// AUTOMATICALLY GENERATED FILE. DO NOT EDIT.

package dispel

var typesTmpl = tmpl(asset.init(asset{Name: "types.go.tmpl", Content: "" +
	"// generated by {{ .Prgm }}; DO NOT EDIT\n\npackage {{ .PkgName }}\n\n{{ $existingTypes := .ExistingTypes }}{{ range .Routes.JSONNamedTypes }}{{/*\nDo not generate the type definition if it's already present in the package\n*/}}{{ if not (hasItem $existingTypes .TypeName) }}{{ printTypeDef . }}{{ end }}\n\n{{ end }}\n" +
	""}))
