// AUTOMATICALLY GENERATED FILE. DO NOT EDIT.

package dispel

var typesTmpl = tmpl(asset.init(asset{Name: "types.go.tmpl", Content: "" +
	"// generated by {{ .Prgm }}; DO NOT EDIT\n\npackage {{ .PkgName }}\n\n{{ $ctx := . }}\n{{ range .Routes.JSONNamedTypes }}{{ $ctx.DisplayType . }}\n\n{{end}}\n" +
	""}))
