package dispel

// Version represents the version of the API generated by dispel.
// A change of the API causes this value to be incremented by 1.
//
// Anything modifying the API of the generated code is considered a change. For example:
//
//  * an interface of the generated code has one of its function changed.
//  * the signature of a non-public function, such as registerRoutes(), changes.
const Version = 1
